const types = {
  // REGISTER_REQUEST: "REGISTER_REQUEST",
  // REGISTER_SUCCESS: "REGISTER_SUCCESS",
  // REGISTER_FAILURE: "REGISTER_FAILURE",
  START_FETCHING_USER: "START_FETCHING_USER",
  STOP_FETCHING_USER: "STOP_FETCHING_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",

  START_FETCHING_POSTS: "START_FETCHING_POSTS",
  STOP_FETCHING_POSTS: "STOP_FETCHING_POSTS",
  GET_CURRENT_POST: "GET_CURRTENT_POST",
  GET_POSTS: "GET_POSTS",

  START_FETCHING_PROFILE: "START_FETCHING_PROFILE",
  STOP_FETCHING_PROFILE: "STOP_FETCHING_PROFILE",
  GET_PROFILE: "GET_PROFILE",
};

export default types;
