const types = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  START_AUTHENTICATION: "START_AUTHENTICATION",
  STOP_AUTHENTICATION: "STOP_AUTHENTICATION",
  GET_USER: "GET_USER",
  GET_POSTS: "GET_POSTS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
};

export default types;
