const types = {
  // REGISTER_REQUEST: "REGISTER_REQUEST",
  // REGISTER_SUCCESS: "REGISTER_SUCCESS",
  // REGISTER_FAILURE: "REGISTER_FAILURE",
  START_FETCHING_USER: "START_FETCHING_USER",
  STOP_FETCHING_USER: "STOP_FETCHING_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  START_FETCHING_POSTS: "START_FETCHING_POSTS",
  STOP_FETCHING_POSTS: "STOP_FETCHING_POSTS",
  GET_POSTS: "GET_POSTS",
  LOGOUT: "LOGOUT",
};

export default types;
